# fly.toml app configuration file generated for diegollanes on 2024-01-04T09:18:47-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "diegollanes"
primary_region = "sea"

[build]
  image = "flyio/hellofly:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
